go-ldap/ldap

conn.go
this unlock line has no reason to exist, and is sure to cause a panic any time it is encountered.
=> remove stupid mutex Unlock()

conn.go
Doing this is not useful and can make the reader() goroutine crash with a nil pointer dereference in ber.ReadPacket.
This bug was seen in real life and caused a server crash.
To easily reproduce the bug/race condition:
```go
package main
import (
"crypto/tls"
"log"
"runtime"
"sync"
"github.com/go-ldap/ldap"
)
const (
addr = "testserver:636"
user = "testuser"
pass = "anything"
)
func routine(i int, wg *sync.WaitGroup) {
defer wg.Done()
ll, err := ldap.DialTLS("tcp", addr, &tls.Config{InsecureSkipVerify: true})
if err != nil {
log.Printf("connection failed: %s", err)
return
}
defer ll.Close()
err = ll.Bind(user, pass)
if err != nil {
return
}
}
func main() {
for n := 0; n < 50; n++ {
var wg sync.WaitGroup
const numRoutines = 100
wg.Add(numRoutines)
runtime.GOMAXPROCS(100)
for i := 0; i < …
```
=> Do not set conn to nil when closing

conn.go
Any panic here can bring down the whole server since these functions are executed into separate goroutines.
Recover and log any panic in those two functions.
(Tested by manually injecting random panics into ber.ReadPacket and ber.Packet.Bytes())
Also minor cleanup to not log read errors while closing a connection.
=> Guard against panic in reader and processMessages

conn.go
By exposing Start() and allowing isTLS to be specified for NewConn() clients can dial their own connections for functionality like timeouts, etc. This addresses Issue #13.
=> Expose Start() and an option to set isTLS in NewConn()

conn.go
This was missed in the previous commit for some reason.  Pull request added to fix the issue where the error (default value assignment) could still get re-assigned an invalid value
=> Fixed else condition to return when error is trapped

conn.go
Currently when an LDAP server returns a result other than success for StartTLS, there is no indication of error to the caller of the function. It seems like an error should be propagated to indicate that a secure connection could not be established.
=> Return error from StartTLS when LDAP response does not indicate success.

filter.go, filter_test.go
Escaped binary data in filter conditions should be converted to their literal values for transport. To reproduce the issue can attempt to query an object in Active Directory using its objectGUID, which is a UUID in its 16 byte form.
=> Convert escaped attribute condition values in filters when building packet

conn.go, error.go, ldap.go
I've added exposed methods that can identify server errors being given from this package. I've also made more use of the `getLDAPResultCode` method, as in some places the extraction was still being done without the method. I'm wondering if some sort of reflection-based unit test would be useful for these methods.
Fixes #35 
@liggitt @johnweldon PTAL
=> added methods to identify server errors

client.go, conn.go
In order to be able to unit-test code that depends on this package, it is extremely useful to have a mock `ldap.Conn` that can be injected into the code. In order for this to be possible, this package must define an interface that represents `ldap.Conn`. I've added the `ldap.Client` interface to the package. This *is not* a breaking change to the API for this package as the reference to the connection is returned as before. Users of the `Client` *will* experience a change, however I think that the change is minimal - the only public member of the `ldap.Conn` struct is a debugging construct that I wouldn't expect consumers of this API to be using. All of the current public functions on `ldap.Conn` are exposed by `ldap.Client` and can be accessed as before.
/cc @johnweldon @liggitt
=> refactored Conn to use a Client interface

search.go, search_test.go
When consumers of this package do unit testing they will invariably mock out LDAP entries. It is useful to expose a nice constructor for this object so that they do not have to do so manually.
/cc @johnweldon @liggitt
=> added constructors for Entry and EntryAttribute

filter.go, filter_test.go
Fixes #28
* adds support for [extensible match](https://tools.ietf.org/search/rfc2254#section-3) sequence (both in CompileFilter and DecompileFilter)
* switched the filter parse to a simple state machine, rather than keying off whether the packet was nil, since attribute parsing could transition to extension matching rule or filter value
* simplified "nextRune" handling to check "currentRune" for performance, then do simple HasPrefix checks. Needed to check variable length prefixes like ":dn:=", ":dn:", etc.
* Fixed encoding of substring match strings and added tests.
Fixes #39
* In cases where we got non-escaped content in the condition, we were iterating on bytes, not runes
* Fixed incorrect multi-byte testcases, and verified byte output matches actual bytes for those characters
=> Add extensibleMatch filter support, fix multi-byte filters

ldap_test.go, search.go
With the current implementation of `Search`, our interaction with this library has been as such: 
- gather knowledge in order to fully qualify an LDAP query
- create a `SearchRequest`
- get a `SearchResponse`
- unpack the response for salient information
The current API for `SearchWithPaging` does not honor this workflow and expects something *other* than a fully-qualified `SearchRequest` to function. This PR adds another API call that allows for a fully qualified search request to be all that is necessary to issue a request to search with client-side page stitching.
@johnweldon @liggitt  PTAL
=> Tolerate existing paging control in SearchWithPaging

error.go, error_test.go
nil packets have been observed when using StartTLS on a connection that
doesn't support it. These previously caused a panic but now will just
result in an unhelpful error.
Mimicking a similar strategy in https://github.com/go-ldap/ldap/blob/07a7330929b9ee80495c88a4439657d89c7dbd87/ldap.go#L89-L93
The nil packets on invalid StartTLS attempts should eventually be
corrected, but this makes the failure much more graceful.
Closes #58
=> Handle nil packets when getting LDAPResultCode

add.go, bind.go, client.go, compare.go, conn.go, conn_test.go, del.go, modify.go, passwdmodify.go, search.go
If the Ldap process is stopped or otherwise unresponsive,
Bind and SimpleBind will block waiting for a response.
This commit adds BindWithTimeout and SimpleBindWithTimeout to
give the developer control over the wait time. The Bind and
SimpleBind will return an error after DefaultTimeout.
=> Apply DefaultTimeout to Bind and SimpleBind

add.go
wrote get methods to struct AddRequest in add.go, as the struct variables are not global, and it would be easy if an add request wants to be compared with another one before populating it.
=> Export AddRequest Struct variables in add.go

conn.go, error_test.go
If the `reader()` goroutine encounters an unexpected error when reading a packet a series of unwinding steps take place:
- The `reader()` goroutine shuts down. A deferred function runs which closes the connection.
- `Close()` sends a MessageQuit message to the `processMessages()` goroutine.
- The `processMessages()` goroutine shuts down. A deferred function runs which closes the results channels for any pending requests.
- These pending request handlers receive a nil `*PacketResponse` because their response channel has been closed. They then return a not-very-helpful error string: `"ldap: channel closed"`.
This patch updates the `reader()` goroutine to set a `closeErr` value on the conn when it encounters an unexpected error reading a packet from the server. The `processMessages()` …
=> Improve handling of connection read errors

add.go, bind.go, compare.go, conn.go, conn_test.go, del.go, modify.go, passwdmodify.go, search.go
This patch introduces a new type called `messageContext` which is now the
return value of `(*Conn).sendMessage()`. The message context object still
contains a channel from which methods like, Add(), Bind(), Search(), etc.,
will receive response packets. It also has a field which holds the message
ID as well as a `done` channel which is used to prevent deadlock in the
`processMessages()` goroutine.
This is accomplished by also changing the `(*Conn).finishMessage()` method to
take a message context and close this `done` channel before sending a
`MessageFinish` packet to the `processMessages()` goroutine.
The `processMessages()` goroutine now has a `messageContexts` map which
replaces the `chanResults` map. Now, rather than sending response packets only
on the response channels, the …
=> Use Message Context

control.go, control_test.go
Fixes #82, fixes #85
* DecodeControl(DecodePacket(bytes)) already worked correctly
* pagingControl.Encode().Data already worked correctly
* DecodeControl(pagingControl.Encode()) failed, since it didn't actually use the bytes in the packet, and just tried to cast the Value field
=> Fix control round-tripping, parsing

control_test.go, ldap.go
* apply similar patch like in #83, closes #86
* add tests for adding ControlDescriptions
=> fix panic in addControlDescriptions()

.travis.yml, dn.go, dn_test.go
RFC2253 explicitly says to ignore unescaped leading and trailing space characters in RDN type/values
RFC4514 (which obsoletes RFC2253) does not indicate leading/trailing space characters are to be ignored, but does say they are to be escaped:
```
3.  Parsing a String Back to a Distinguished Name
The string representation of Distinguished Names is restricted to
UTF-8 [RFC3629] encoded Unicode [Unicode] characters.  The structure
of this string representation is specified using the following
Augmented BNF [RFC4234] grammar:
distinguishedName = [ relativeDistinguishedName
*( COMMA relativeDistinguishedName ) ]
relativeDistinguishedName = attributeTypeAndValue
*( PLUS attributeTypeAndValue )
attributeTypeAndValue = attributeType EQUALS attributeValue
attributeType = descr / numericoid …
```
=> Ignore unescaped leading/trailing spaces in RDN type/value

dn.go, dn_test.go
Adds `Equal` method to `DN`, `RelativeDN`, and `AttributeTypeAndValue` types
Adds `AncestorOf` method to `DN`
Based on rfc4517 4.2.15 (distinguishedNameMatch):
```
4.2.15.  distinguishedNameMatch
The distinguishedNameMatch rule compares an assertion value of the DN
syntax to an attribute value of a syntax (e.g., the DN syntax) whose
corresponding ASN.1 type is DistinguishedName.
The rule evaluates to TRUE if and only if the attribute value and the
assertion value have the same number of relative distinguished names
and corresponding relative distinguished names (by position) are the
same.  A relative distinguished name (RDN) of the assertion value is
the same as an RDN of the attribute value if and only if they have
the same number of attribute value assertions and each attribute
value …
```
=> Add comparison methods for DN/RDN/AttributeTypeAndValue

Makefile, atomic_value.go, atomic_value_go13.go, conn.go
This should fix some various data races, mostly around the `isClosing` / `closeErr` fields in the `Conn` struct.  I've taken a similar route as #74, but with full support for older versions of Go that don't support the `sync/atomic.Value` struct.
=> Fix race conditions

error.go
Hi,
This PR only fixes a small typo to the word “Network” in error.go.
Kind regards,
Vincent
=> Fix typo in error.go file

example_test.go
Hi,
While playing the userAuthentication example as-is, I end up with the following error because of a typo:
```
2017/03/04 17:51:08 LDAP Result Code 201 "": ldap: finished compiling filter with extra at end: (uid=my.uid))
```
This PR just removes the extra `&`  in the search filter. (Tested against bind9).
Thanks
Joseph
=> Cosmetics: Fix example typo

filter.go, filter_test.go
=> fix unbalanced parenthesis panic when compiling filter

dn.go, dn_test.go
=> fix dn parsing without attr or value

bind.go, error.go, ldap_test.go
This is normally used for unauthenticated bind, and
https://tools.ietf.org/html/rfc4513#section-5.1.2 recommends:
> Clients SHOULD disallow an empty password input to a Name/Password
> Authentication user interface
=> Require explicit intention for empty password.

.travis.yml, Makefile, bind.go, conn.go, conn_test.go, debug.go, dn.go, error_test.go, example_test.go, ldap.go, passwdmodify.go, search_test.go
Commits are separated for easier review. Commit messages have details on the thought process.
I just came across this package tonight, so I'm unfamiliar with its use in real scenarios. I may also be unfamiliar with nuances in the code. If someone could try this in their setup or recommend which use cases need tests I'll happily add them.
/cc @johnweldon @liggitt
=> fix race conditions in conn.go

bind.go, compare.go, conn.go, control.go, dn.go, filter.go, ldap.go, modify.go, search.go
closes #122
The repo was relicensed under MIT in https://github.com/mmitton/ldap/commit/9031c63a92b917c423331f055304e168d8f28789 but individual files still referred to the BSD license.
This picks the corrected file headers from https://github.com/mmitton/ldap/commit/5c6d51ed24aa5a12e58df30524a1008b364a0cf3
=> Remove stale references to BSD license

.travis.yml, Makefile, conn.go, conn_test.go, debug.go, dn.go, error_test.go, example_test.go, ldap.go, passwdmodify.go, search_test.go
=> Update v2 branch with race fixes

bind.go, del.go, search.go
During the code reshuffle in #126 at bind time a call to encodeControls
was added. Unfortunately, the safety check around calling it when there
are no controls to encode were omitted from this call (unlike in del.go
and search.go). As a result the packet was always getting control
characters added even if there were none to encode.
I also modified the checks in del.go and search.go to be a little safer;
rather than check for a nil slice, it also will do the right thing when
the slice is not nil but there are no entries.
=> Fix control packets being encoded when none exist on bind

modify.go
Updates ModifyRequest to allow the order of changes to be specified rather than grouped by operation.
As defined in [rfc4511](https://tools.ietf.org/html/rfc4511#section-4.6):
```
- changes: A list of modifications to be performed on the entry.  The
entire list of modifications MUST be performed in the order they
are listed as a single atomic operation.
```
=> Allow order of changes in ModifyRequest to be specified

CONTRIBUTING.md
Let's expand this document with our Contribution Guidelines and processes.
=> Add an initial Contributions Guideline document

bind.go, compare.go, control.go, control_test.go, dn.go, dn_test.go, ldap.go, passwdmodify.go, search.go
functions which were using ber.DecodePacket() now return an error also.
fixes #77
=> Ber errors

.travis.yml, dn_test.go, example_test.go, filter_test.go, moddn_test.go
Some of the *_test.go files are pointing to the external package "gopkg.in/ldap.v2". This is not the expected behavior of unittests and it is not consistent with other unittests inside the library.
=> Fix unittests pointing to the external package "gopkg.in/ldap.v2"

compare.go
Fixes https://github.com/go-ldap/ldap/issues/139
Without the patch I get
```
2018/08/07 14:59:47 Received unexpected message 0, false
LDAP Response: (Universal, Constructed, Sequence and Sequence of) Len=122 "<nil>"
Message ID: (Universal, Primitive, Integer) Len=1 "0"
Extended Response: (Application, Constructed, 0x18) Len=93 "<nil>"
(Universal, Primitive, Enumerated) Len=1 "2"
(Universal, Primitive, Octet String) Len=0 ""
(Universal, Primitive, Octet String) Len=86 "00000057: LdapErr: DSID-0C0C0F50, comment: Error decoding ldap message, data 0, v3839\x00"
(Context, Primitive, 0x0A) Len=22 "<nil>"
(bool) false
(*errors.errorString)(0xc42014fa90)(unable to read LDAP response packet: unexpected EOF)
LDAP Result Code 200 "": ldap: connection closed
```
=> Stop Compare causing "Error decoding ldap message"

add.go, bind.go, compare.go, conn.go, del.go, error.go, error_test.go, ldap.go, ldap_test.go, moddn.go, modify.go, passwdmodify.go, search.go
Here are the changes mentioned in https://github.com/go-ldap/ldap/pull/178#discussion_r202878918.
As the branch I had previously made changes on had moved ahead. The merge followed by the changes closed the old issue for some reason.
Let me know if these changes make sense and are readable - or I can start from a fresh checkout and do the changes fresh.
=> Issue 177 matcheddn

conn.go
As it currently stands, there is no guarantee that the requestTimeout variable on a Conn structure is going to be aligned to a 64-bit boundary. As golang/go#599 is not fixed as of yet, it is still the caller's responsibility to ensure that is the case.
This pull request should resolve issues #185 and #195 by moving requestTimeout to the very beginning of the structure. The alternative would be to manually pad the structure, and that offers no guarantees of no regression occurring due to the length of the structure changing in future versions.
=> conn: Ensure 64-bit alignment for atomics on 32-bit platforms

conn.go, ldap_test.go
This change exposes the internal tls connection state, following the pattern taken by `net/smtp`: https://golang.org/pkg/net/smtp/#Client.TLSConnectionState
This makes it possible to inspect the certificate chain returned by ldap servers that only offer StartTLS. For example, I just used my fork to make a quick cli tool to help with maintenance on the certificates of some OpenLDAP instances.
=> Add ldap.TLSConnectionState()

control.go, control_test.go
Hi, this is PR for cases, if Control doesn't require value, for example
```
control := ldap.NewControlString("1.3.6.1.4.1.4203.666.5.12", false, "")
controls := []ldap.Control{}
controls = append(controls, control)
```
**1.3.6.1.4.1.4203.666.5.12** is for RelaxControl, but if I didn't use this check, ldap server will throw error
```
LDAP Result Code 2 "Protocol Error": relax control value not absent
```
I've checked few libs in Python, C#, Java, they omit values for some controls which do not require values.
Thanks
#212
=> Added check for ControlValue string check

conn.go
=> Prevent negative waitgroup panic by `Add`ing first.

conn.go, request.go, v3/conn.go, v3/request.go
This is useful for those who fork this repo and change debug's printpacket to use ber.WritePacket instead. that way we only need make a change in one place of code and we don't need change it everywhere else. Makes it more consistent
=> Fix printing packets references to use Debug instead of Ber

conn.go
Fix the handling of a race where the connection is closed between the isClosing test at the top of sendMessageWithFlags, and a subsequently ignored test in sendProcessMessage.
We were encountering this rarely in our CI runs where for some reason the LDAP server drops the connection just after Dial but in the middle of our first GetUserBindDN call.  The message fails to send but the sendMessage returns nil, then message receiving stalls reading from the responses channel for a message that will never arrive.
=> sendMessage closing race fix

bind.go, go.mod, go.sum, v3/bind.go, v3/go.mod, v3/go.sum
Hello again! 
`go-ntlmssp` merged in my PR for processing challenges with hashes only (https://github.com/Azure/go-ntlmssp/pull/27), so I wanted to quickly add this functionality to `go-ldap` also.
I added another exported function, `NTLMBindWithHash` that performs an NTLM bind with a valid  NTLM hash in hex format. The NTLMChallengeBind flow is the same, it just checks whether password or hash is set to determine how to compute the response.
Oh I also committed in updated `go.mod` and `go.sum` (which I missed last PR)
=> Add ability to bind with only NTLM Hash instead of password

search.go, v3/search.go
The %w fmt verb for errors isn't valid for older versions of Go.
=> Fix regression with %w verb

.github/workflows/pr.yml
=> Dropped test coverage support from legacy go versions: go1.5 go1.6

moddn.go, v3/moddn.go
This allows setting LDAP Request controls with modify DN operation.
Tested against an LDAP server and checked that controls were being sent.
make all - works
=> Add an API to specify LDAP Request controls with modifyDN operation

conn.go, v3/conn.go
Since asn1-ber ends up reading single bytes, we wrap the network connection into a buffered reader to avoid a syscall for every read.
This is the same thought that guided https://github.com/go-asn1-ber/asn1-ber/pull/31, but as we had to discover in https://github.com/go-asn1-ber/asn1-ber/issues/33, that approach was fundamentally flawed.
This should give us equal speed gains, but without losing any bytes this time.
(I introduced the change in both conn.go and v3/conn.go, though I'm not sure that is correct - feedback welcome)
=> introduce buffering for connection reader

examples_test.go, v3/examples_test.go
The authentication example does not escape the username before constructing the search filter. This makes it prone to a LDAP injection attack.
=> escape username in auth example

bind.go, v3/bind.go
if ntlmsspChallenge is empty or shorter than 7 bytes, the '[:7]' will cause a panic:
```
panic(0xbe1a40, 0xc00013ec60)
runtime/panic.go:969 +0x1b9
github.com/go-ldap/ldap/v3.(*Conn).NTLMChallengeBind(0xc0002da300, 0xc000382d80, 0x0, 0x0, 0x0)
github.com/go-ldap/ldap/v3@v3.2.4/bind.go:489 +0xf46
github.com/go-ldap/ldap/v3.(*Conn).NTLMBind(...)
github.com/go-ldap/ldap/v3@v3.2.4/bind.go:441
```
Thus, avoid the panic by doing a length check.
This was tested against an LDAP server not supporting NTLM authentication. After the change, I get an expected error:
```
LDAP Result Code 7 "Auth Method Not Supported": unknown authentication method
```
=> NTLMChallengeBind: avoid panic

control.go, control_test.go, v3/control.go, v3/control_test.go
This PR adds the Microsoft control LDAP_SERVER_LINK_TTL_OID to the LDAP v3 suite. 
The purpose of this is to view TTLs of group memberships with associated expiry times.
More information on the control can be found at the following link:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/f4f523a8-abc0-4b3a-a471-6b2fef135481?redirectedfrom=MSDN
=> Add Microsoft Control LDAP_SERVER_LINK_TTL_OID

dn.go, v3/dn.go
Since v3 ldap we have case insensitive search in parallel to a case sensitive search:
https://github.com/go-ldap/ldap/pull/111
I would like to propose to add an EqualFold function in parallel to Equal function in dn.go on AttributeTypeAndValue.
So we can not only search in case sensitive but also compare RDNs.
=> Add EqualFold function on AttributeTypeAndValue.

unbind.go, v3/unbind.go
As requested in #324, this PR implements the `unbindRequest` as specificed in [RFC4511](https://datatracker.ietf.org/doc/html/rfc4511#section-4.3). Personally, I don't see why this option shouldn't be added to allow users to gracefully close the connection to the DSA without unwillingly throwing errors on one side.
When the function is called, all outstanding / waiting requests will return an error, since the underlying connection will be closed anyways.
=> Add Unbind Request

search.go, v3/search.go
@stefanmcshane  As mentioned in #319, here's my PR for improving the part of the attribute extraction after an LDAP search result has been returned by the server. 
I did [some benchmarks](https://gist.github.com/xNevo/e4faf1a90bb610e59ec622e3e6e62558), as requested. The differences become more significant the more attributes are parsed. Regardless of the performance: I think this code should be moved into it's own fucnction anyway for better readability.
=> Improve search attribute extraction

debug.go, v3/debug.go
Debugger prints debug-level messages via std `log` but prints packets via `os.Stdout`, so it makes impossible to use the `Output` from the global `log`, e.g. `zap` provides [single point of configuration even for the global `log`](https://godoc.org/go.uber.org/zap#RedirectStdLog), so still could be used for libraries logging setup.
Pass `log#Writer()` to the `ber` packet writer func.
Partly resolves https://github.com/go-ldap/ldap/issues/164
=> Change debugger to write packet via log's Writer (#1)

dn.go, dn_test.go, v3/dn.go, v3/dn_test.go
=> allow using `;` as RDN separator according to rfc2253

go.mod, v3/go.mod
The PR is intended to be complementary to PR #367 and set the minimum Go version to 1.14 in the go.mod files.
=> Update minimum Go version to 1.14

bind.go, v3/bind.go
Actually, the function `UnauthenticatedBind` allows an anonymous or a username without password with a SimpleBindRequest.
This PR implements the same feature for an NTLMBind with the help of `NTLMUnauthenticatedBind`
=> Allow NTLM authentication without a password

client.go, v3/client.go
It seems the `Client` interface hasn't been updated in a while. Some methods which have been added to `Conn` were missing  😅
=> Add missing `Client` interface methods

control.go, control_test.go, v3/control.go, v3/control_test.go
This PR implements the control type "Subtree Delete", see https://datatracker.ietf.org/doc/html/draft-armijo-ldap-treedelete-02 for detailed informations on this.
This replaces PR #346 , as the author unfortunately doesn't respond / seems to be inactivate looking at his GitHub profile
=> Implement Subtree delete control type

modify.go, passwdmodify.go, request.go, v3/modify.go, v3/passwdmodify.go, v3/request.go
This implements returning the referral for the modify operation. Tested against a Microsoft Active Directory Read-only Domain Controller. 
This also adds anti-panic guards in edge cases where the packet is malformed. This could be refactored to return an error or be removed entirely depending on what is considered to be desired/appropriate by maintainers. I also utilized the ASN.1 BER consts to check tag types in relevant code sections as I think this is more readable, and factorized the code into a single method rather than duplicating it.
Decisions:
=> feat: return referrals for modify operation

search.go, search_test.go, v3/search.go, v3/search_test.go
Based on the ground work of #304 this PR adds two additional supported variable types: int and []byte.
=> added int and []byte type to entry unmarshal

dn.go, dn_test.go, v3/dn.go, v3/dn_test.go
This is bascially a try to revive #104. AFAICS the only missing piece (apart from rebasing) was to duplicate the code to the v3 folder.
=> Add String() methods to DN and its subtypes

conn.go, v3/conn.go
=> Fix request timeout handling

ldap.go, ldap_test.go, v3/ldap.go, v3/ldap_test.go
This adds a function to escape distinguished names, as described in RFC4514.
The use case is to allow building valid DNs from untrusted input, for example if the group name is user supplied like in the following example:
```
func ModifyGroup(groupName string) {
groupCN := fmt.Sprintf("cn=%s,ou=groups,dc=example,dc=org", ldap.EscapeDN(groupName))
ldap.NewModifyRequest(groupCN, nil)
...
}
```
=> Add function to escape distinguished names

conn.go, v3/conn.go
This is actually a deprecated RFC, however Active Directory relies on it for server discovery.
Without this patch CLDAP is possible via directt use of the the deprecated `Dial` function with a UDP network connection. This patch adds the same support to the DialURL function via the 'cldap' URI scheme.
See https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/8ebcf782-87fd-4dc3-8585-1301569dfe4f
and https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/895a7744-aff3-4f64-bcfa-f8c05915d2e9 for MS documentation on this.
=> Add CLDAP (RFC1798 UDP/Connectionless) support to DialURL

conn.go, v3/conn.go
I once added `DialWithTLSDialer` as wrapper, not realizing that everything necessary to define both the dialer and `tlsconfig` already exists. This PR renames the non-exported fields for better readability and marks `DialWithTLSDialer` as deprecated, but keeps it intact
=> chore: deprecate unnecessary wrapper for `DialWithDialer` and `DialWithTLSConfig`

modify.go, passwdmodify.go, request.go, v3/modify.go, v3/passwdmodify.go, v3/request.go
This adjusts the packet referral decoding behavior to more appropriately handle edge cases and allows to more easily obtain the underlying packet in the event of a decoding error. Instead of matching ASN.1 BER packets on the tag for referrals we match on the class and type. This is particularly important in regards to OpenLDAP which returns a ASN.1 BER Generalized Time tag for referrals.
While I think this is a bug on the OpenLDAP side it's also perfectly reasonable in my opinion to handle this here as it's relatively easy to do so.
=> fix: packet referral decoding

search.go, v3/search.go
Fixes #411 and removes bogus debug message (`Looking for Paging Control...`)
=> fix: error and search result handling in SearchWithPaging

control.go, debug.go, dn.go, moddn.go, request.go, unbind.go, v3/control.go, v3/debug.go, v3/dn.go, v3/moddn.go, v3/request.go, v3/unbind.go
Lint checks now pass.
Submitting these as their own PR, so as not to confuse the content of another patch I'd like to submit.
This contains the lint fixes required to get `make` to run cleanly, as per README.md - hopefully there's nothing too controversial here.
=> Lint/gofmt fixes.

v3/control.go, v3/control_test.go
Hey,
I open a PR to implements server side sorting some months ago (https://github.com/go-ldap/ldap/pull/358) and close it for actually no reason :(
I change some variables names which is not clear while reading my old PR. Don't hesitate to tell me if something is wrong in the code I'll fix it :p
=> implement server side sorting controls (rfc2891)

dn.go, dn_test.go, v3/dn.go, v3/dn_test.go
This fixes an issue where attributes with equal chars in the value would not be correctly parsed. As we only set the AttributeTypeAndValue's Type field once and we reset it on the step to the next AttributeTypeAndValue we can assume if this field already has a value that it should not consider it the type/value separator.
Fixes #416
=> fix: parsedn not handling attributes with equal char in value

conn.go, conn_test.go, v3/conn.go, v3/conn_test.go
We are using this library as part of a network probe, where we attempt to make an unauthenticated bind and gather some basic information about a host that appears to be listening on the standard LDAP ports. We found that in some rare cases, the connection may be killed out-of-band or black holed by an intermediary firewall.
In these cases, we identified a couple of deadlocks in the `v3.Conn.Close` and `v3.messageContext.sendResponse` methods:
```
goroutine 2045 [chan receive, 2586 minutes]:
github.com/go-ldap/ldap/v3.(*Conn).Close(0xc00d6c4d00)
/home/runner/go/pkg/mod/github.com/go-ldap/ldap/v3@v3.4.4/conn.go:270 +0xff
```
```
goroutine 11123636 [select, 2589 minutes]:
github.com/go-ldap/ldap/v3.(*messageContext).sendResponse(...) …
```
=> Fix deadlocks caused by invalid connection state

add.go, client.go, conn.go, del.go, moddn.go, modify.go, v3/add.go, v3/client.go, v3/conn.go, v3/del.go, v3/moddn.go, v3/modify.go
This replaces the package-wide logger, used in places like processMessages and reader, and returns an error instead. For backwards compatibility, errors returned from goroutine functions are stored in `Conn.err` and can get retrieved through `Conn.GetLastError`.
=> fix: return errors upon panics or receiving unexpected responses

search.go, search_test.go, v3/search.go, v3/search_test.go
this uses the github.com/go-asn1-ber/asn1-ber package to parse the timestamp
=> add unmarshalling of generalizedTimestamp and DN

client.go, control.go, control_test.go, examples_test.go, search.go, v3/client.go, v3/control.go, v3/control_test.go, v3/examples_test.go, v3/search.go
This pull request enables go-ldap to search with DirSync control.
This request was referenced below, but the Cookie process was changed from the following request. The reason is to allow the search to resume from the Cookie.
Please check the test for the usage.
reference: 
* https://github.com/go-ldap/ldap/pull/110
* https://learn.microsoft.com/ja-jp/previous-versions/windows/desktop/ldap/ldap-server-dirsync-oid?redirectedfrom=MSDN
=> feat: enable DirSync control in search operation

response.go, v3/response.go
The previous change is merged from #440. 
I'm implementing #422 using the search asynchronous feature. I found a deadlock issue with the low-sized buffered channel in my local environment. When the buffered channel is full, a goroutine waits to send to the channel. But sometimes, searchResponse.Next() occurs deadlock since the messageMutex cannot get a lock in Conn.GetLastError().
While working at #440, I found Conn.err is a race condition. So I added messageMutex.Lock() code, which causes a deadlock issue with certain conditions (e.g., a low-sized buffered channel). That makes a more complicated problem.
~This code is young, and we can revert quickly.~
=> Fix a deadlock issue using search asynchronously

Makefile, fuzz_test.go
using [go-fuzz](https://go.dev/security/fuzz) for fuzz testing of `ldap`
"PR / Go 1.16.x PR Validate . (Modules) (pull_request) Failing after 17s:"
```
vet: ./dn_test.go:294:29: F not declared by package testing
Error: Process completed with exit code 2.
```
Go-fuzz was introduce  in `Go 1.18`.
=> [Fuzzing] Add fuzz testing

error.go, error_test.go, v3/error.go, v3/error_test.go
This PR addresses multiple panics in `GetLDAPError` as described in Issue #453.  It does so by checking the response children for the expected tag type before attempting to extract the value. The PR also adds tests that should trigger all three panics if the fix is incorrect.
=> Fix panics in GetLDAPError

v3/control.go
In SyncRequest cookie is optional, so do not add cookie if empty
=> ControlSyncRequest Encode: cookie optionality 

v3/error.go, v3/error_test.go
ldap.Error wraps an underlying error, but doesn't interoperate with errors.Is or errors.As. This change makes it easier to detect things like an LDAP error caused due to a network timeout.
=> Add support for Go 1.13's errors.Is/As functions

client.go, control.go, control_test.go, examples_test.go, search.go, v3/client.go, v3/control.go, v3/control_test.go, v3/examples_test.go, v3/search.go
I'm now developing an application to connect the Windows AD server and get entries. Thanks to #436, I can use DirSync() method to search. As my requirement, I have to handle several ten thousand entries. This is not so big, but waste of memory at once. I noticed #440 provides a search asynchronous feature, so I can search without getting all entries at once.
I looked into the code in DirSync() method and tested it. I refactored some minor changes for maintainability.
I made it as below. It works in my environment.
```go
// DirSyncDirSyncAsync performs a search request and returns all search results
// asynchronously. This is efficient when the server returns lots of entries.
func (l *Conn) DirSyncAsync(
ctx context.Context, searchRequest *SearchRequest, bufferSize int,
flags, maxAttrCount …
```
=> Refactor DirSync search process

go.mod, go.sum, v3/go.mod, v3/go.sum
As follow up to the newest release of [go-asn1-ber v1.5.5](https://github.com/go-asn1-ber/asn1-ber/releases/tag/v1.5.5). Update the dependencies for both v3 and the project root
=> chore: update go-asn1-ber to v1.5.5

conn.go, conn_test.go, v3/conn.go, v3/conn_test.go
Fixes the race conditions on request_timeout.
=> fix request timeout race condition

fuzz_test.go
I investigated why DATA RACE occurred.
```
WARNING: DATA RACE
Write at 0x000000c3c628 by goroutine 38:
github.com/go-ldap/ldap.FuzzParseDN()
/home/runner/work/ldap/ldap/fuzz_test.go:14 +0x32
testing.fRunner()
/opt/hostedtoolcache/go/1.18.10/x64/src/testing/fuzz.go:700 +0x168
testing.runFuzzTests.func1()
/opt/hostedtoolcache/go/1.18.10/x64/src/testing/fuzz.go:5[20](https://github.com/go-ldap/ldap/actions/runs/6781841980/job/18432888679#step:5:21) +0x47
```
Fuzz tests also run as unit tests, so the module global variable shouldn't change in a test function.
```go
ber.MaxPacketLengthBytes = 65536
```
I fix this conflict by adding TestMain(), which handles a setup process before all tests. Now, all tests run with `ber.MaxPacketLengthBytes` limitation. Does it make sense?
See also #472.
* …
=> Fix DATA RACE as a result of changing ber's module global variable for fuzz tests

error.go, error_test.go, v3/error.go, v3/error_test.go
This might break compatibility, but I guess that most developers want this behavior. What do you think?
=> IsErrorAnyOf should match the given result code even if the error is wrapped

.github/workflows/pr.yml
I found a deprecated warning on Annotations.
* https://github.com/go-ldap/ldap/actions/runs/6924243142
> Lint
> 
> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This warning is from the old core library in golangci-lint-action. So, update it.
* https://github.com/golangci/golangci-lint-action/pull/578
=> Fix deprecated warning on GitHub Actions

search.go, search_test.go, v3/search.go, v3/search_test.go
This PR adds `*string` as available type for `SearchResult.Unmarshal`. Closes #475
=> feat: extend SearchResult `Unmarshal` to support *string as field type (#475)

search.go, v3/search.go
This PR adds const declaration for representing children scope value 3.
=> feat: Add support for children scope choice const

search.go, v3/search.go
This PR adds a new optional attribute that, when enabled, enforces a hard limit on the maximum number of parsed entries from a search request to the requested SizeLimit. This behaviour is disabled by default.
See #431 for why this might be necessary.
=> feat: Add `EnforceSizeLimit` to enforce the specified search request size limit (fixes #431)

conn.go, control.go, v3/conn.go, v3/control.go
Refer to https://go.dev/wiki/Deprecated
The right way to mark a function as deprecated is to use `Deprecated:` as the beginning of a doc comment paragraph.
This ensures that various tools (such as static checks) pick up the deprecation information.
=> fix: mark functions as deprecated with doc comment

dn.go, dn_test.go, ldap.go, v3/dn.go, v3/dn_test.go, v3/ldap.go
This PR reworks the `ParseDN` function, which has been very resource consuming for reading one byte at a time and couldn't handle certain characters. This implementation is based upon inteons PR for cert-manager, which wasn't fully compatible with the RFC 4514.
This PR also:
* Moves an unexported variable to a function scoped constant to free up the name `hex`
* Renames the imported package `enchex` to it's original name `hex` for better readabilty
* Improves the readability of `ParseDN` test failures
If this resolves the reported problems, we can revert #466.
=> feat: Refactor `ParseDN` function to fix resource usage and invalid parsings (fixes #487)

dn.go, dn_test.go, fuzz_test.go, v3/dn.go, v3/dn_test.go
I additionally made some extra changes to the String() functions to make the round tripping work.
PTAL
~~NOTE: I think there might be a few changes that are not required but still included. I need some extra time to find them.~~
UPDATE: I removed the unnecessary code
@cpuschma
=> Add tests to parseDN (fuzzing, roundtrip ...)

dn.go, dn_test.go, v3/dn.go, v3/dn_test.go
This PR replaces the Go asn1 library in the `decodeEncodedString` function to decode values with ASN1 BER instead. The replacement of the returned error should be ok, as there hasn't been a release with the new implementation of `ParseDN' yet.
See  [RFC4514 Section 2.4](https://www.ietf.org/rfc/rfc4514.html#section-2.4):
> If the AttributeType is of the dotted-decimal form, the
AttributeValue is represented by an number sign ('#' U+0023)
character followed by the hexadecimal encoding of each of the octets
of the BER encoding of the X.500 AttributeValue.  This form is also
used when the syntax of the AttributeValue does not have an LDAP-
specific ([[RFC4517], Section 3.1](https://www.ietf.org/rfc/rfc4517#section-3.1)) string encoding defined for it, or
the LDAP-specific string encoding is …
=> fix: Replace DER with ASN1 BER encoding when parsing distinguishedNames

conn.go, v3/conn.go
This reverts the the prematurely deprecation of the `Start` function, because some requirements cannot be implemented via the DialOpts (see #507). This PR reverts this, but adds a warning because of the original intention (see #356)
=> Revert #499: Mark public Start function as deprecated

conn.go
As pointed out in https://github.com/go-ldap/ldap/issues/520#issue-2319762177, the subdirectory v3 has been out of sync. This PR copies all missing changes to the root directory.
=> chore: Fix desynced root and v3 directory (fixes #520)

v3/bind.go, v3/go.mod
This PR adds the `Negotiator` field to `NTLMBindRequest` which lets users specify a custom NTLM implementation. This is needed because `github.com/Azure/go-ntlmssp` is a very limited NTLM implementation with no support for features such as channel binding which may be required to connect to AD LDAP.
=> Allow users to specify a custom NTLM negotiator

v3/control.go, v3/go.mod, v3/go.sum
In LDAP, boolean has stricter encoding rules than in BER. Need to use NewLDAPBoolean so that the value is FF.
https://docs.ldap.com/specs/rfc4511.txt section 5.1 
>  If the value of a BOOLEAN type is true, the encoding of the value
octet is set to hex "FF".
=> use ldap boolean for dirsync control.criticality

v3/examples_test.go
update `DirSync` and `DirSyncAsync` example codes to use `DialURL` instead of the already deprecated `Dial` function
=> chore: update `DirSync` and `DirSyncAsync` example codes

v3/search.go, v3/search_test.go
As requested in #530, this is rather simple but hopefully straightforward implementation for a custom entry unmarshal function.  This should enable users to create their own Unmarshaler for search results if, for example, special handling of the attribute tags is required
=> feat: add initial support for custom entry unmarshaler

v3/go.mod, v3/go.sum, v3/gssapi/sspi.go, v3/gssapi/sspi_test.go
This PR relates to: https://github.com/alexbrainman/sspi/pull/18
This PR should also not be merged before above PR is merged since it is strictly dependant on those changes.
In newer microsoft active directory versions, channel binding token is on by default, causing clients to fail to authorize.
These changes gives an option to enable the security context to be updated with a channel binding token.
I have tested manually against active directory servers that have this feature on and off, and after these changes along with above PR, I was able to connect and authorize as usual.
It is hard to write tests for things like this that talks to the operating system, but any pointers to how I can improve my tests would be appreciated, otherwise I hope this us up to the standard of the lib in …
=> Add RFC 5929 channel binding support for SSPI client
